checking for sublime

diff --git a/dotbin/sublime b/dotbin/sublime
--- a/dotbin/sublime
+++ b/dotbin/sublime
@@ -1,4 +1,9 @@
 #! /bin/sh
 
 unset TERM
-exec /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl "$@"
+if [ -f /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl ]; then
+  exec /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl "$@"
+else
+  echo "$SHELL: $0: command not found"
+  exit 127
+fi
